apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 755484098059.dkr.ecr.us-east-1.amazonaws.com/shopping-site-earphones:81663fa3e38110f43efd5cda1d03f78f24cb640d
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: earphones-service
  labels:
    app: earphones
spec:
  type: ClusterIP
  selector:
    app: earphones
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
