apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 755484098059.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlegrocery:81663fa3e38110f43efd5cda1d03f78f24cb640d
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: googlegrocery-service
  labels:
    app: googlegrocery
spec:
  type: ClusterIP
  selector:
    app: googlegrocery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
